### PR TITLE
fix(save-artifact-on-failure)

### LINKED ISSUE #5: Figure out how to save the generated microsite as a build github actions artefact, when the performance budgets are broken
At present, we only save the generated artefacts from a greenspeed run, if a site is running inside criteria defined in the budget.js file.

You really want to know _why_ a build failed, so having access to the generated artefacts is pretty important, when you go over budget

I'm not sure how to retain and upload the generated files in the event of a failed run, but it _must_ be possible.

Anyone ?

### PR DESCRIPTION
**Pull request by dvelasquez**
This PR adds the conditional `always()` to allow to package the result even if the budget is not met. Example:

```yaml
- name: Archive generated report as an artefact for later review
        uses: actions/upload-artifact@v2
        if: always() #This does the trick
        with:
          name: report
          path: report
```

Also, this PR adds the [Cache GitHub Action](https://github.com/actions/cache/blob/main/examples.md#node---npm) which enables caching of the installed dependencies. In order to use this, versioning of `package-lock.json` is required.

Resolves #5

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Thanks @dvelasquez, this looks great!

**Comment by mrchrisadams** [comment]
@dvelasquez I'm not sure I understand the significance of the config-failure workflow, to go with the regular config one.

Are they there to confirm that both a failing test _and_ a passing test generate the browsable artefact microsite thing?

**Comment by dvelasquez** [comment]
Exactly. If you want you can delete the fail action or we could look for a way to fail if it's a success (since the intended outcome is fail the budget target).

**Comment by mrchrisadams** [comment]
Cool, thanks David. I've merged this in now.

**Pull request merged**
